### ISSUE TITLE
Designación de roles

### ISSUE THREAD

**Issue by Torukuran** [Brilliant-Minds-Grupo-5/Mascota-Feliz-#1]
Cada miembro del equipo estará encargado de un rol (líder, diseñador de software, diseñador UI, tester, administrador de configuración y desarrollador)

**Comment by Tigucaro** [comment]
Nombre del Equipo: Brilliant Minds 
Roles:
Líder de Equipo: Carolina Gutiérrez Zapata
Administración de la configuración: Gina Esmeralda Rodríguez Peña 
Diseñador de Software: Dayana Sánchez Moreno
Diseñador de Interfaz de Usuario: Carlos Eduardo Correa Hernández
Tester: Leandro Cano Castaño
