### ISSUE TITLE
Reunión con el tutor

### ISSUE THREAD

**Issue by Torukuran** [Brilliant-Minds-Grupo-5/Mascota-Feliz-#2]
Se organiza encuentro con el tutor el día 21/10/2022 a las 5:30

**Comment by Tigucaro** [comment]
Reunión con el tutor Juan Sebastián Gómez el 21 de Octubre de 2022

![Image](https://user-images.githubusercontent.com/111239053/197424277-9be29442-1754-4d94-85e9-de7cff4d205e.png)
