### ISSUE TITLE
Elaboración de diagrama

### ISSUE THREAD

**Issue by Torukuran** [Brilliant-Minds-Grupo-5/Mascota-Feliz-#3]
Luego de realizar la lectura del proyecto por parte de cada miembro, se elabora en conjunto el diseño del diagrama de clases.

**Comment by Tigucaro** [comment]
Diagrama de Clases

![Image](https://user-images.githubusercontent.com/111239053/197423794-f5696319-b879-4c16-9c4a-fe0d4c0e154a.png)

**Comment by Tigucaro** [comment]
Modelo Entidad Relación

![Image](https://user-images.githubusercontent.com/111239053/197424251-64fca73e-e15a-4772-877d-b0304ce65dd0.png)
